use_frameworks!

platform :ios, '9.0'


flutter_application_path = '../jyd_fluttermodule'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'iOS2FlutterPageRoute_Example' do
  
  install_all_flutter_pods(flutter_application_path)

  pod 'iOS2FlutterPageRoute', :path => '../'


end
